version: '2.3'
services:
  geoserver:
    image: pcic/geoserver:latest
    container_name: geoserver_bc_regions
    ports:
      - "30124:8080"
    volumes:
      - type: bind
        source: /storage/data/projects/comp_support/geoserver_data/2.17.x/web.xml
        target: /opt/geoserver/webapps/geoserver/WEB-INF/web.xml
        read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/geoserver_data/2.17.x/users.xml
        target: /opt/geoserver/data_dir/security/usergroup/default/users.xml
        read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/geoserver_data/2.17.x/global.xml
        target: /opt/geoserver/data_dir/global.xml
        read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/geoserver_data/2.17.x/masterpw.digest
        target: /opt/geoserver/data_dir/security/masterpw.digest
        read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/geoserver_data/2.17.x/workspaces_bc_regions
        target: /opt/geoserver/data_dir/workspaces/bc_regions
        read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/geoserver_data/2.17.x/data_bc_regions
        target: /opt/geoserver/data_dir/data/bc_regions
        read_only: true
    mem_limit: 2g
    memswap_limit: 2g
    restart: unless-stopped

networks:
  default:
    external:
      name: pcicbr0
