version: '3.8'
services:
  geoserver:
    image: pcic/geoserver:2.25.0
    container_name: geoserver-2.25.0
    ports:
      - "30669:8080"
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 2g
    restart: unless-stopped

    volumes:
      - type: bind
        source: /storage/data/projects/comp_support/geoserver/dev/geoserver-2.25.0/data_dir
        target: /opt/geoserver/data_dir
      - type: bind
        source: /storage/data/projects/comp_support/geoserver/dev/geoserver-2.25.0/data_dir/workspaces
        target: /opt/geoserver/data_dir/workspaces
      - type: bind
        source: /storage/data/projects/comp_support/geoserver/dev/geoserver-2.25.0/users.xml
        target: /opt/geoserver/data_dir/security/usergroup/default/users.xml
        read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/geoserver/dev/geoserver-2.25.0/global.xml
        target: /opt/geoserver/data_dir/global.xml
        read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/geoserver/dev/geoserver-2.25.0/masterpw.digest
        target: /opt/geoserver/data_dir/security/masterpw.digest
        read_only: true
      - type: bind
        source: /storage/data/projects/comp_support/geoserver/dev/geoserver-2.25.0/web.xml
        target: /opt/geoserver/webapps/geoserver/WEB-INF/web.xml

networks:
  default:
    name: pcicbr0
    external: true
